// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/voidrunr/go-url-shortener/internal/model"
)

// Shortener is an autogenerated mock type for the Shortener type
type Shortener struct {
	mock.Mock
}

type Shortener_Expecter struct {
	mock *mock.Mock
}

func (_m *Shortener) EXPECT() *Shortener_Expecter {
	return &Shortener_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: _a0
func (_m *Shortener) Resolve(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shortener_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type Shortener_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - _a0 string
func (_e *Shortener_Expecter) Resolve(_a0 interface{}) *Shortener_Resolve_Call {
	return &Shortener_Resolve_Call{Call: _e.mock.On("Resolve", _a0)}
}

func (_c *Shortener_Resolve_Call) Run(run func(_a0 string)) *Shortener_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Shortener_Resolve_Call) Return(_a0 string, _a1 error) *Shortener_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Shortener_Resolve_Call) RunAndReturn(run func(string) (string, error)) *Shortener_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Shorten provides a mock function with given fields: _a0, _a1
func (_m *Shortener) Shorten(_a0 string, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shortener_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type Shortener_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Shortener_Expecter) Shorten(_a0 interface{}, _a1 interface{}) *Shortener_Shorten_Call {
	return &Shortener_Shorten_Call{Call: _e.mock.On("Shorten", _a0, _a1)}
}

func (_c *Shortener_Shorten_Call) Run(run func(_a0 string, _a1 string)) *Shortener_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Shortener_Shorten_Call) Return(_a0 string, _a1 error) *Shortener_Shorten_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Shortener_Shorten_Call) RunAndReturn(run func(string, string) (string, error)) *Shortener_Shorten_Call {
	_c.Call.Return(run)
	return _c
}

// ShortenBatch provides a mock function with given fields: _a0, _a1
func (_m *Shortener) ShortenBatch(_a0 []model.BatchItem, _a1 string) ([]model.BatchItem, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ShortenBatch")
	}

	var r0 []model.BatchItem
	var r1 error
	if rf, ok := ret.Get(0).(func([]model.BatchItem, string) ([]model.BatchItem, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]model.BatchItem, string) []model.BatchItem); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BatchItem)
		}
	}

	if rf, ok := ret.Get(1).(func([]model.BatchItem, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shortener_ShortenBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortenBatch'
type Shortener_ShortenBatch_Call struct {
	*mock.Call
}

// ShortenBatch is a helper method to define mock.On call
//   - _a0 []model.BatchItem
//   - _a1 string
func (_e *Shortener_Expecter) ShortenBatch(_a0 interface{}, _a1 interface{}) *Shortener_ShortenBatch_Call {
	return &Shortener_ShortenBatch_Call{Call: _e.mock.On("ShortenBatch", _a0, _a1)}
}

func (_c *Shortener_ShortenBatch_Call) Run(run func(_a0 []model.BatchItem, _a1 string)) *Shortener_ShortenBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.BatchItem), args[1].(string))
	})
	return _c
}

func (_c *Shortener_ShortenBatch_Call) Return(_a0 []model.BatchItem, _a1 error) *Shortener_ShortenBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Shortener_ShortenBatch_Call) RunAndReturn(run func([]model.BatchItem, string) ([]model.BatchItem, error)) *Shortener_ShortenBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: _a0
func (_m *Shortener) ListByUser(_a0 string) ([]model.URL, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]model.URL, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []model.URL); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shortener_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type Shortener_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - _a0 string
func (_e *Shortener_Expecter) ListByUser(_a0 interface{}) *Shortener_ListByUser_Call {
	return &Shortener_ListByUser_Call{Call: _e.mock.On("ListByUser", _a0)}
}

func (_c *Shortener_ListByUser_Call) Run(run func(_a0 string)) *Shortener_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Shortener_ListByUser_Call) Return(_a0 []model.URL, _a1 error) *Shortener_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Shortener_ListByUser_Call) RunAndReturn(run func(string) ([]model.URL, error)) *Shortener_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewShortener creates a new instance of Shortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *Shortener {
	mock := &Shortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
