template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/voidrunr/go-url-shortener/internal/handler:
    interfaces:
      Shortener:
        config:
          dir: internal/handler/mocks
          filename: "{{ .InterfaceName | kebabcase }}_mock.go"
          pkgname: mocks
